outdir: results/RBP
rRNA_fasta: rRNA.fa # or directly give the rRNA STAR index under the key rRNA_index
# rRNA_index: 
star_index: /home/kenchen/db/star/GRCh38-gencode.STAR_overhang100
genome_fa: /home/kenchen/db/gencode/GRCh38/GRCh38.primary_assembly.genome.fa
chromsize: /home/kenchen/db/gencode/GRCh38/GRCh38.primary_assembly.genome.fa.chromsize # format: [chrom]\t[size], e.g, https://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.chrom.sizes
split_bam_py: /home/kenchen/Documents/ARTR-seq-snakemake/demo/split_bam_by_strand.py
homer:
  extsize: 20
  background: /home/kenchen/db/gencode/GRCh38/v46/regions/gencode.v46.gene.bed # optional


data:
  path: /data/user/kenchen/projects/ARTR-seq-custom/data/raw
  samples: 
    A.HepG2.40k.RBFOX2.rep1:
      R1: /data/user/kenchen/data/GEO/GSE226161_ARTR-seq_YuXiao/SRR23628463.fastq.gz
      amount: 40k
      cell: HepG2
      condition: RBFOX2
      group: A
      input:    ## For ARTR-seq samples, specifiy the input samples
        - A.HepG2.40k.Input.rep2
        - A.HepG2.40k.Input.rep1
        - A.HepG2.40k.Input.rep3
      rep: rep1
      strandness: F
    A.HepG2.40k.Input.rep1:
      R1: /data/user/kenchen/data/GEO/GSE226161_ARTR-seq_YuXiao/SRR23628470.fastq.gz
      amount: 40k
      cell: HepG2
      condition: Input
      group: A
      input: null # For input samples, set to null or skip this key
      rep: rep1
      strandness: F
    A.HepG2.40k.Input.rep2:
      R1: /data/user/kenchen/data/GEO/GSE226161_ARTR-seq_YuXiao/SRR23628469.fastq.gz
      amount: 40k
      cell: HepG2
      condition: Input
      group: A
      input: null
      rep: rep2
      strandness: F
    A.HepG2.40k.Input.rep3:
      R1: /data/user/kenchen/data/GEO/GSE226161_ARTR-seq_YuXiao/SRR23628468.fastq.gz
      amount: 40k
      cell: HepG2
      condition: Input
      group: A
      input: null
      rep: rep3
      strandness: 
      strandness: F
    NO_F1_Don_HeLa_rep1:
      R1: NO_F1_Don_HeLa_rep1-R1-P16B19.fq.gz
      R2: NO_F1_Don_HeLa_rep1-R2-P16B19.fq.gz
      cell: HeLa
      concentration: F1
      rbp: 'NO'
      rep: rep1
      strandness: FR
    NO_F1_Don_HeLa_rep2:
      R1: NO_F1_Don_HeLa_rep2-R1-P16B20.fq.gz
      R2: NO_F1_Don_HeLa_rep2-R2-P16B20.fq.gz
      cell: HeLa
      concentration: F1
      rbp: 'NO'
      rep: rep2
      strandness: FR
    NO_F1_Don_HeLa_rep3:
      R1: NO_F1_Don_HeLa_rep3-R1-P16B21.fq.gz
      R2: NO_F1_Don_HeLa_rep3-R2-P16B21.fq.gz
      cell: HeLa
      concentration: F1
      rbp: 'NO'
      rep: rep3
      strandness: FR
    NO_F1_Don_HepG2_rep1:
      R1: NO_F1_Don_HepG2_rep1-R1-P16B1.fq.gz
      R2: NO_F1_Don_HepG2_rep1-R2-P16B1.fq.gz
      cell: HepG2
      concentration: F1
      rbp: 'NO'
      rep: rep1
      strandness: FR
    NO_F1_Don_HepG2_rep2:
      R1: NO_F1_Don_HepG2_rep2-R1-P16B2.fq.gz
      R2: NO_F1_Don_HepG2_rep2-R2-P16B2.fq.gz
      cell: HepG2
      concentration: F1
      rbp: 'NO'
      rep: rep2
      strandness: FR
    NO_F1_Don_HepG2_rep3:
      R1: NO_F1_Don_HepG2_rep3-R1-P16B3.fq.gz
      R2: NO_F1_Don_HepG2_rep3-R2-P16B3.fq.gz
      cell: HepG2
      concentration: F1
      rbp: 'NO'
      rep: rep3
      strandness: FR
    RBFOX2_F1_Don_HepG2_rep1:
      R1: RBFOX2_F1_Don_HepG2_rep1-R1-P16B4.fq.gz
      R2: RBFOX2_F1_Don_HepG2_rep1-R2-P16B4.fq.gz
      cell: HepG2
      concentration: F1
      rbp: RBFOX2
      rep: rep1
      strandness: FR
      input:
        - NO_F1_Don_HepG2_rep1
        - NO_F1_Don_HepG2_rep2
        - NO_F1_Don_HepG2_rep3
    RBFOX2_F1_Don_HepG2_rep2:
      R1: RBFOX2_F1_Don_HepG2_rep2-R1-P16B5.fq.gz
      R2: RBFOX2_F1_Don_HepG2_rep2-R2-P16B5.fq.gz
      cell: HepG2
      concentration: F1
      rbp: RBFOX2
      rep: rep2
      strandness: FR
      input:
        - NO_F1_Don_HepG2_rep1
        - NO_F1_Don_HepG2_rep2
        - NO_F1_Don_HepG2_rep3
    RBFOX2_F1_Don_HepG2_rep3:
      R1: RBFOX2_F1_Don_HepG2_rep3-R1-P16B6.fq.gz
      R2: RBFOX2_F1_Don_HepG2_rep3-R2-P16B6.fq.gz
      cell: HepG2
      concentration: F1
      rbp: RBFOX2
      rep: rep3
      strandness: FR
      input:
        - NO_F1_Don_HepG2_rep1
        - NO_F1_Don_HepG2_rep2
        - NO_F1_Don_HepG2_rep3
